// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


var mySize = "Medium";

var otherSize = "Large";

var wrongSize = "M";

exports.mySize = mySize;
exports.otherSize = otherSize;
exports.wrongSize = wrongSize;
/* No side effect */
