// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function payment(principal, apr, $staropt$star, param) {
  var years = $staropt$star !== undefined ? $staropt$star : 30;
  var r = apr / 12.0 / 100.0;
  var n = Caml_int32.imul(years, 12);
  var powerTerm = Math.pow(1.0 + r, n);
  return principal * (r * powerTerm) / (powerTerm - 1.0);
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

var amount = payment(10000.00, 5.0, undefined, /* () */0);

console.log("Amount per month: $", amount.toFixed(2));

var amount2 = payment(25000.00, 7.5, 15, /* () */0);

console.log("Amount per month: $", amount2.toFixed(2));

var apr = 7.5;

var principal = 25000.00;

exports.payment = payment;
exports.toFixed = toFixed;
exports.amount = amount;
exports.apr = apr;
exports.principal = principal;
exports.amount2 = amount2;
/* amount Not a pure module */
