// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


var match = true;

var discount = match ? 0.05 : 0.10;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Prix avant réduction: " + (String(total) + " €"));

console.log("Prix après réduction: " + (String(afterDiscount) + " €"));

var qty = 7;

var price = 14.50;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
