// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


var poem = "The Boy stood on the burning deck,\n  Whence all but he had fled;\nThe flames that lit the battle\'s wreck... ";

console.log(poem);

exports.poem = poem;
/*  Not a pure module */
