// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


var total = 13.12 + 0.6215 * 5 - 11.37 * Math.pow(20, 0.16) + 0.3965 * 5 * Math.pow(20, 0.16);

console.log("At temperature " + (String(5) + (" degrees C and wind speed " + (String(20) + (" km/hr\n  the wind chill temperature is " + (String(total) + "."))))));

var temp = 5;

var windSpeed = 20;

exports.temp = temp;
exports.windSpeed = windSpeed;
exports.total = total;
/* total Not a pure module */
